# Generated by Django 3.2.9 on 2021-11-07 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_buy',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 6, 23, 4, 45, 622702), null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_buy',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 6, 23, 4, 45, 624169), null=True, verbose_name='Fecha'),
        ),
    ]
