# Generated by Django 3.2.9 on 2021-11-07 02:10

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_auto_20211106_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=180, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=180, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_buy',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 6, 23, 9, 33, 892101), null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_buy',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 6, 23, 9, 33, 893668), null=True, verbose_name='Fecha'),
        ),
    ]
