# Generated by Django 3.2.9 on 2021-11-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_auto_20211106_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Monto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Monto'),
            preserve_default=False,
        ),
    ]
