# Generated by Django 3.2.9 on 2021-11-07 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0005_auto_20211106_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Havings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción')),
                ('value', models.DecimalField(decimal_places=2, max_digits=500, verbose_name='Valor del activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
        ),
        migrations.CreateModel(
            name='FixedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('days', models.PositiveSmallIntegerField(verbose_name='Días')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de interés')),
                ('starting_amount', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Monto Inicial')),
                ('ending_amount', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Monto Final')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plazo Fijo',
                'verbose_name_plural': 'Plazos Fijos',
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción')),
                ('value', models.DecimalField(decimal_places=2, max_digits=500, verbose_name='Valor del pasivo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pasivo',
                'verbose_name_plural': 'Pasivos',
            },
        ),
    ]
