# Generated by Django 3.2.9 on 2021-11-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_duty_fixedterm_havings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(blank=True, null=True, verbose_name='Periodo')),
                ('total_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True, verbose_name='Gastos totales')),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True, verbose_name='Ingresos totales')),
                ('monthly_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True, verbose_name='Balance Mensual')),
            ],
            options={
                'verbose_name': 'Auditoria Mensual',
                'verbose_name_plural': 'Auditoria Mensual',
            },
        ),
    ]
