# Generated by Django 3.2.9 on 2021-11-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_monthlyaudit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date_buy',
        ),
        migrations.RemoveField(
            model_name='income',
            name='date_buy',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
